name: Blog

dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - xlrd
  - pytables
  - lxml
  - beautifulsoup4
  - html5lib
  - networkx
  - scipy
  - pip
  - pip:
    - empiricaldist



