name: ProbablyOverthinkingIt
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - xlrd
  - pytables
  - lxml
  - beautifulsoup4
  - html5lib
  - networkx
  - scipy
  - statsmodels
  - lifelines
  - git-lfs
  - jupyter-book
  - pip
  - pip:
    - empiricaldist
